version: '3'

volumes:
  appenv: 
    driver: local
    
services:
  db:
    image: postgres

  web:
    build: 
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ../../my_store:/code
      - appenv:/oscar
    env_file: ./conf.env
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db