# Generated by Django 2.1.10 on 2019-07-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190708_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, max_length=255, upload_to='images/products/%Y/%m/', verbose_name='Featured Image'),
        ),
    ]
