# Generated by Django 2.1.8 on 2019-05-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190521_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(max_length=255, upload_to='images/products/%Y/%m/', verbose_name='Original'),
        ),
    ]
